### ISSUE TITLE
HomePage

### ISSUE THREAD

**Issue by danilocecilia** [bmvantunes/youtube-2020-march-nextjs-part5#5]
I've noticed you have a src/HomePage.tsx, is it required to have it there? Since you on the index.tsx you are importing the container/homepage.

**Comment by bmvantunes** [comment]
This video is part5 of the Next.js tutorial. That code comes from part 1, 2, 3 and 4 :)

Mainly we did that because we wanted both pages to work
www.myapp.com
and
www.myapp.com/homepage
